name: Semgrep

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    uses: pcvantol/djconnect/.github/workflows/djconnect-semgrep-ci.yml@main
    with:
      continue-on-error: true
